version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dockerfile
    ports:
      - 3000:3000
